#!/usr/bin/env python3
"""
Regenerate the .agents/skills/triz-innovation/ mirror of the triz-innovation skill.

The mirror is a self-contained copy of .claude/skills/triz-innovation/ so that
Codex (and any other agent reading .agents/) can run every script without
referencing .claude/ paths. Every copied text file (.md, .py, .json, .csv) has
the literal prefix `.claude/skills/triz-innovation` rewritten to
`.agents/skills/triz-innovation`, and the mirror's SKILL.md carries a GENERATED
banner plus a note that the branch tree is copied verbatim from source.

Usage:
    python scripts/build_mirror.py            # rebuild the mirror
    python scripts/build_mirror.py --check    # compare (no changes), exit 1 on drift

The repo root is computed from this script's own location (one parent up), so
it works from any working directory.

Standard library only — Python 3.8+.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path
from typing import Optional

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SOURCE = _REPO_ROOT / ".claude" / "skills" / "triz-innovation"
_MIRROR = _REPO_ROOT / ".agents" / "skills" / "triz-innovation"

_PREFIX_SRC = ".claude/skills/triz-innovation"
_PREFIX_DST = ".agents/skills/triz-innovation"

_BANNER = (
    "<!-- GENERATED by scripts/build_mirror.py — do not edit; edit the source under "
    ".claude/skills/triz-innovation/ -->\n"
    "> GENERATED by scripts/build_mirror.py — do not edit; edit the source under "
    ".claude/skills/triz-innovation/\n"
)

_BRANCHES_NOTE = (
    "\n## Branches\n\nThe `branches/` tree in this mirror is copied verbatim from the source\n"
    "`.claude/skills/triz-innovation/branches/` — edit the source and re-run\n"
    "`python scripts/build_mirror.py` to regenerate this mirror.\n"
)

_TEXT_EXTS = {".md", ".py", ".json", ".csv"}


def _rewrite(text: str) -> str:
    """Rewrite the source prefix to the mirror prefix in a text file's content."""
    return text.replace(_PREFIX_SRC, _PREFIX_DST)


def _expected_files() -> dict[Path, str]:
    """Return {mirror-relative-path: content} that a fresh build would produce.

    The content includes the prefix rewrite for every text file, the GENERATED
    banner prepended to SKILL.md, and the branches note appended to SKILL.md.
    """
    expected: dict[Path, str] = {}

    for subdir in ("references", "scripts", "branches"):
        src_dir = _SOURCE / subdir
        if not src_dir.is_dir():
            continue
        for path in sorted(src_dir.rglob("*")):
            if path.is_dir():
                continue
            if "__pycache__" in path.parts or path.suffix == ".pyc":
                continue
            rel = path.relative_to(_SOURCE)
            content = path.read_text(encoding="utf-8")
            if path.suffix in _TEXT_EXTS:
                content = _rewrite(content)
            expected[rel] = content

    skill_path = _SOURCE / "SKILL.md"
    if skill_path.is_file():
        skill_content = _rewrite(skill_path.read_text(encoding="utf-8"))
        expected[Path("SKILL.md")] = _BANNER + skill_content + _BRANCHES_NOTE

    return expected


def build() -> None:
    """Wipe the mirror's SKILL.md + subdirs and write fresh copies from source."""
    for name in ("SKILL.md", "references", "scripts", "branches"):
        target = _MIRROR / name
        if target.is_dir():
            shutil.rmtree(target)
        elif target.exists():
            target.unlink()

    for rel, content in _expected_files().items():
        target = _MIRROR / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def _mirror_files() -> set[Path]:
    """Relative paths of every file currently present in the mirror."""
    files: set[Path] = set()
    for subdir in ("references", "scripts", "branches"):
        target = _MIRROR / subdir
        if not target.is_dir():
            continue
        for path in target.rglob("*"):
            if path.is_file() and "__pycache__" not in path.parts:
                files.add(path.relative_to(_MIRROR))
    if (_MIRROR / "SKILL.md").is_file():
        files.add(Path("SKILL.md"))
    return files


def check() -> list[str]:
    """Return a list of drift problems; empty when the mirror is in sync.

    Compares the current mirror against what a fresh build would produce
    (banner-aware). Does NOT modify anything.
    """
    problems: list[str] = []
    expected = _expected_files()

    for rel, content in expected.items():
        target = _MIRROR / rel
        if not target.is_file():
            problems.append(f"missing: {rel}")
        elif target.read_text(encoding="utf-8") != content:
            problems.append(f"drifted: {rel}")

    for rel in sorted(_mirror_files()):
        if rel not in expected:
            problems.append(f"extra: {rel}")

    return problems


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass

    args = sys.argv[1:]
    if "--check" in args:
        problems = check()
        if problems:
            for problem in problems:
                print(problem)
            sys.exit(1)
        print("Mirror is in sync")
        sys.exit(0)

    build()
    print(f"Rebuilt {_MIRROR} from {_SOURCE}")


if __name__ == "__main__":
    main()
